### ISSUE TITLE
A Gem's Gemfile.lock should NOT be in source control.

### ISSUE THREAD

**Issue by stevenharman** [radar/guides#14]
The [Gem Development](https://github.com/radar/guides/blob/master/gem-development.md) guide says that the `Gemfile.lock` file "_should always be checked into version control._" However, this is _NOT_ true for Gems. For Applications, like your Rails apps, Sinatra apps, etc., it is true. The same does not go for Gems.

For clarification, please see Yehuda's guidance on the roles of `.gemspec`, `Gemfile`, and `Gemfile.lock` files: [Clarifying the roles of .gemspec and Gemfile](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/)

**Comment by Jwan622** [comment]
I don't understand his reason. What if my gem depends on say Rails 3 and is not compatible with Rails 4?

**Comment by nicolasmccurdy** [comment]
Then you should specify a version string for Rails 3 in your Gemfile, while still leaving Gemfile.lock ignored by git. Gemfile.lock is meant to be a full version lock for all dependencies specifically for deploying software. If you depend on certain version ranges of a gem to ensure compatibility, that belongs in Gemfile, not Gemfile.lock.

**Comment by nilbus** [comment]
More specifically, for gems, version constraints belong in the gemspec.

**Comment by nilbus** [comment]
More background on the rationale:

Since the gem command only respects the dependency version constraints named in the gemspec, not Gemfile.lock, the presence of a Gemfile.lock is more likely to keep gem maintainers unaware that gem users will have newer versions of dependencies than developers, which may be incompatible.

Also, I'm commenting here because this issues shows up in Google search results. I understand that this issue and the gem development guide are several years old, and that although the [gem-development directory][1] contains a Gemfile.lock, the actual guide only explicitly suggests tracking Gemfile.lock when _using_ the gem (in an app).

[1]: https://github.com/radar/guides/tree/master/gem-development/foodie

**Comment by radar** [comment]
I would gladly accept a patch here that improved the wording around this section, advocating for `Gemfile.lock` to not be committed to version control. @nilbus: is that something that you'd want to do?
